name: OFRP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: rokibhasansagar/slimhub_actions@main
      
      - run: |
          sudo apt-get update -qq
          sudo apt-get install -y git repo rsync python3 cpio gzip -qq

      - name: Sync Source
        run: |
          cd /home/runner
          git clone https://gitlab.com/OrangeFox/sync.git
          cd sync
          chmod +x orangefox_sync.sh
          ./orangefox_sync.sh --branch 12.1 --path /home/runner/fox_12.1
          echo "Done syncing"
          ls /home/runner/fox_12.1/
          echo "SRC=/home/runner/fox_12.1" >> $GITHUB_ENV

      - name: Clone Device Tree
        run: |
          cd $SRC
          rm -rf device/huawei/mrr_w29
          git clone https://github.com/qzj112223/device_huawei_mrr_w29 -b main device/huawei/mrr_w29

      - name: Build
        run: |
          cd $SRC
          source build/envsetup.sh
          lunch omni_mrr_w29-eng
          make recoveryimage -j$(nproc --all)

      - uses: softprops/action-gh-release@v1
        with:
          files: $SRC/out/target/product/mrr_w29/recovery.img
          name: mrr_w29-OFRP-${{ github.run_id }}
          tag_name: r-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
